spring:
  application:
    name: topography-service
  threads:
    virtual.enabled: true
  grpc:
    server:
      port: 9092
  datasource:
    url: jdbc:postgresql://localhost:5432/aafo_telemetry
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8082

logging:
  level:
    root: INFO
    com.aafo.topography: DEBUG
    io.grpc: WARN
